services:
  table-flow-postgres:
    image: postgres:17.2
    env_file:
      - ../env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - tf-pgdata:/var/lib/postgresql/data
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: unless-stopped
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
  #     PGADMIN_DEFAULT_PASSWORD: strong-password
  #   volumes:
  #     - tf-pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - table-flow-postgres
  table-flow-be:
    build:
      context: ../table-flow-be
      dockerfile: ./Dockerfile
    env_file:
      - ../table-flow-be/.env
    ports:
      - '3001:3001'
    volumes:
      - ../table-flow-be:/app
      - /app/node_modules
    depends_on:
      - table-flow-postgres
  table-flow-fe:
    build:
      context: ../table-flow-fe
      dockerfile: ./Dockerfile
    # env_file:
    #   - ../table-flow-fe/.env
    ports:
      - '3000:3000'
    volumes:
      - ../table-flow-fe:/app
      - /app/node_modules
    depends_on:
      - table-flow-be
volumes:
  tf-pgdata:
  tf-pgadmin-data: